services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: ksbl-bot-backend
    restart: unless-stopped
    network_mode: host
    command: uvicorn api:app --host 0.0.0.0 --port 8010
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./data:/app/data
      - ./prompts:/app/prompts
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
