ANTHROPIC_API_KEY = "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"
GOOGLE_API_KEY = "AIzaSyDucATXkwa4i5QK_YlEJT5F9CwEyqcTf64"
VOYAGE_API_KEY = "pa-U7wAhRh5MhWy3dWI9ncVYARIUOySvb5PQrFXzTRLEVU"
HUGGINGFACE_API_KEY = "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"
GROQ_API_KEY = "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"
OPENROUTER_API_KEY = "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"